#!/usr/bin/env zsh

# already bootstraped?!
if [ -f $HOME/.arch/bootstrap_done ]
then
  exit 0
fi

if [ ! -f /usr/bin/sudo ]
then 
  echo 'please install sudo and re-run the script'
  exit 1
fi

echo 'start bootstrapping\n'

# base pkgs
echo 'installing base pkgs \n'
sudo pacman -S --needed --noconfirm \
  openssh \
  unzip \
  base-devel \
  zsh \
  &> /dev/null

# yay
echo 'installing yay \n'
test ! -d $HOME/git/yay \
  && mkdir -p $HOME/git \
  && cd $HOME/git \
  && git clone https://aur.archlinux.org/yay.git &> /dev/null \
  && cd yay \
  && makepkg -si --needed --noconfirm &> /dev/null \
  && cd $HOME \
  &> /dev/null

# programming languages
echo 'installing programming languages \n'
yay -S --needed --noconfirm \
  rustup \
  go \
  tinygo \
  # includes language server
  dart \
  nodejs \
  npm \
  deno \
  python \
  python-pip \
  wasmer \
  protobuf \
  # language server
  # lua
  lua-language-server \
  # python
  pyright \
  # tailwindcss
  tailwindcss-language-server \
  # html, css, eslint, json
  vscode-langservers-extracted \
  &> /dev/null

echo 'configuring programming languages \n'
# go
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest &> /dev/null
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest &> /dev/null
# dart
dart pub global activate protoc_plugin &> /dev/null
# rust
rustup default stable &> /dev/null
## language server for rust
rustup component add rls rust-analysis rust-src &> /dev/null

# developer environment
echo 'installing developer environment \n'
yay -S --needed --noconfirm \
  tmux \
  neovim \
  ripgrep \
  k9s \
  kubectl \
  aws-cli \
  helm \
  lazygit \
  mqttui \
  wireshark-cli \
  qmk \
  &> /dev/null

echo 'configuring developer environment \n'
# vim
nvim +PlugInstall +qall &> /dev/null
# tmux
tmux start-server &> /dev/null \
  && tmux new-session -d &> /dev/null \
  && ~/.tmux/plugins/tpm/scripts/install_plugins.sh &> /dev/null \
  && tmux kill-server &> /dev/null

if [ ! $DOTFILES_INJECTED -eq 0 ]
then 
  echo 'bootstrapping finished! have fun.\n'
  touch $HOME/.arch/bootstrap_done
  exit 0
fi

# window manager & system pkgs
echo 'installing window manager & system pkgs \n'
yay -S --needed --noconfirm \
  i3-wm \
  # picom-git \
  hsetroot \
  alacritty \
  # rxvt-unicode \
  pulseaudio \
  xorg-server \
  # polybar \
  # feh \
  # xorg-xsetroot \
  xorg-xrandr \
  xorg-xinit \
  # rofi \
  netctl \
  wifi-menu \
  fstrim \
  bluez \
  bluez-utils \
  noto-fonts \
  noto-fonts-emoji \
  noto-fonts-cjk \
  noto-fonts-extra \
  # ttf-hack-nerd \
  # ttf-font-awesome \
  ttf-nerd-fonts-symbols \
  ttf-nerd-fonst-symbols-mono \
  &> /dev/null

# user pkgs
echo 'installing user pkgs \n'
yay -S --needed --noconfirm \
  hugo \
  htop \
  mc \
  gotop \
  podman \
  podman-compose \
  aardvark-dns \
  netavark \
  buildah \
  skopeo \
  google-chrome \
  minikube \
  libvirt \
  qemu-base \
  &> /dev/null

echo 'enabling services \n'
sudo sudo systemctl enable bluetooth.service

echo 'configuring shell environment \n'
# regenerate font cache
fc-cache -f &> /dev/null

echo 'configuring infrastructure environment \n'

# podman
sudo touch /etc/subuid /etc/subgid
sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(whoami)
sudo podman system migrate
# sudo echo "$USER ALL=(ALL) NOPASSWD: /usr/bin/podman" >> /etc/sudoers

# minikube (podman driver needs v1.26)
minikube config set driver podman
# minikube config set driver kvm2
# minikube config set rootless true

# libvirt
sudo usermod -a -G libvirt $(whoami)
sudo virsh net-autostart default

echo 'configuring user environment \n'
# qmk
mkdir -p $HOME/git \
  && cd $HOME/git \
  && git clone -b dztech/dz60rgb_ansi/v2 git@github.com:matsp/qmk_firmware.git &> /dev/null \
  && cd qmk_firmware \
  && make git-submodule &> /dev/null


# touch file to signal the successfull bootstrap
touch $HOME/.arch/bootstrap_done

### HINT: load keymap for mechanical keyboard with ansi layout and mapped umlaute
# localectl set-x11-keymap us altgr-intl altgr-intl nodeadkeys
