version: "3.8"
services:
  shell:
    env_file: ~/.docker/dotfiles/.env
    build:
      context: ${DOCKERFILE_GIT}
      args:
        USER: ${USER_NAME}
        DOTFILES_GIT_URL: ${DOTFILES_GIT_URL}
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    tty: true
    container_name: dotfiles
    volumes:
      - ~/.ssh:${CONTAINER_SSH_DIR}
      - projects-data:/projects
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  projects-data:
