
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 15
builtin_box_drawing = false

# [font.glyph_offset]
# x = 0
# y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# [font.offset]
# x = 0
# y = 0

[scrolling]
history = 1000

[general]
import = ["~/.config/alacritty/colors.toml"]
